export const fullcourtHex = {
  pageBg: '#ffffff',
  sectionBg: '#f8fafc',
  cardBg: '#ffffff',
  border: '#e2e8f0',
  text: '#1f2937',
  textSoft: '#475569',
  textMuted: '#64748b',
  accentBg: '#dbeafe',
  accentText: '#1e3a8a',
  pointBlue: '#2563eb',
  pointGreen: '#2f855a',
  pointGreenSoft: '#dcfce7',
  pointAmber: '#b7791f',
  pointAmberSoft: '#fef3c7',
  buttonPrimaryBg: '#1d4ed8',
  buttonPrimaryHover: '#1e40af',
  buttonPrimaryText: '#ffffff',
  buttonOutlineBorder: '#bfdbfe',
  buttonOutlineHover: '#eff6ff',
  footerBg: '#1f2937',
} as const
